![GDG school](Images/Artboard_2.png)

# **GDG school ML workshop**
### Table of content 


1.   **Machine learning :**


*   What's Machine learning ?

*   The difference between ML and traditional programming.
*   AI, ML and Deep learning.
2.  **Machine learning pipeline**
*  Collect data
*  Preparing data
* Choosing model 
* Training
* Evaluation 
3.  **Solving problems using AI**


# 1.   **Machine learning :** 
*   **What's Machine learning ?**


### Some examples of machine learning 
#   **Is that ML ?** 
### autonomus cars
![autonomus cars](Images/giphy.gif) 
Autonomous cars apply a wide range of techniques to function. These include statistics, robotics, and machine learning.

### online ad optimization ?
In order to optimize ads online, machine learning and statistics are needed to deliver the correct type of ads to the right audience, and to measure the effectiveness of the optimization.

### Customer service chatbot
![](Images/PastelFriendlyGibbon-size_restricted.gif)
A customer service chatbot will need machine learning to process human produced language in such a way that it can act on it.


* #   **The difference between ML and traditional programming.**

![Traditionnal programming](Images/2020-01-09_232844.png)

We express rules in a programming language. These act on data and our program provides answers. We write rules in any programming language and those will act on data we get answers

![Machine learning](Images/2020-01-09_232855.png)
What if we could provide a lot of labeled answers and it inferences rules? the model will try to determine, from the data, what the distinct patterns that denote a particular case are.
### When this happens ?
So our model will have a bunch of data in the training phase and now using rules infered from the training phase he'll capable to make "*predictions*"
![training phase](Images/2020-01-09_232915.png)


### Generalization 
> The goal of ML is never to make “perfect” guesses, because ML deals in domains where there is no such thing. The goal is to make guesses that are good enough to be useful.

![meme](Images/75481841_2450909828504762_89711125100232704_n.jpg)




#  **AI, ML and Deep learning.**

Simply said: Artificial intelligence (AI) is the ability of a computer program or a machine to think like humans do.
AI is using technology to do things which used to require human intelligence, for example problem solving or learning, and will likely shape our future more than any technology that has come before.
Machine learning (ML) is a subfield of AI and gives machines the skills to ‘learn’ from examples without being explicitly programmed to do so. Deep learning (DL) is a specialized ML technique that mimics the behavior of the human brain and enables machines to train themselves to perform tasks.
![AI,ML and DL](Images/Intro_to_ML.png)


Source ( [schoolofdisruption](https://schoolofdisruption.com/exponential-technologies/artificial-intelligence/))


# 2.  **Machine learning pipeline :**

     To define our problem, we need to answer these questions:

  * What is the main objective? What are we trying to predict?
  * What are the target features?
  * What is the input data? Is it available?
  * What kind of problem are we facing?

## *  **Collecting Data** 
This is the first real step towards the real development of a machine learning model, collecting data. This is a critical step that will cascade in how good the model will be, the more and better data that we get, the better our model will perform.
## *  **Preparing the Data**
Before beginning to train model, we should transform our data in a way that can be fed into a Machine Learning model. The most common techniques are:

 * Dealing with missing data
  * Feature Scaling
 *  Splitting Data into Subsets
* # **Choosing Model**
* ### Supervised learning :
Instead of manually writing down exact rules to do the classification, the point in supervised machine learning is to take a number of examples, label each one by the correct label, and use them to “train” an AI method to automatically recognize the correct label for the training examples.
![supervised ](Images/4_1_supervised-learning.093ef920.svg)
* ### Unsupervised learning :
In unsupervised learning, the correct answers are not provided. This makes the situation quite different since we can't build the model by making it fit the correct answers on training data. It also makes the evaluation of performance more complicated since we can't check whether the learned model is doing well or not.
* ### Reinforcement learning: 
Commonly used in situations where an ML agent like a self-driving car must operate in an environment and where feedback about good or bad choices is available with some delay. Also used in games where the outcome may be decided only at the end of the game.
![graphes  ]()

![alt image sklearn ](Images/MLhG2.png)

* ## **Training** 🏋️‍♂️
We will by the simpliest model you could have.
Linear regression is better suited in situations where the output variable can be any number like the price of a product, the distance to an obstacle, the box-office revenue of the next Star Wars movie, and so on.
* # Simple Linear Regression
Simple Linear Regression is a statistical model, widely used in ML regression tasks, based on the idea that the relationship between two variables can be explained by the following formula:
![ y=ax+b ](Images/y=ax+b+e.png)
![alt grapheLR ](Images/grapheLR.png)

If we have more than one input, variables can be explained by the following formula:  Y=ax1+bx2+cx3+⋯+K+ ε

![alt matrixForm ](Images/matrix_form.png)


![alt estima ](Images/estima.png)
![alt estimB ](Images/estimB.png)
![alt gradient ](Images/gradientDescent.png)

* ## Logistic Regression

We can turn the linear regression method’s outputs into predictions about labels. The technique for doing this is called logistic regression. We take the output from linear regression, which is a number, and predict one label A if the output is greater than zero, and another label B if the output is less than or equal to zero. For example: 
   * To predict whether an email is spam (1) or (0)
   * Whether the tumor is malignant (1) or not (0)
   * Handwritten digits, in which case there are ten possible labels.

* # Neural Network 
* ### The human nervous system
Human nervous system consists of billions of neurons. These neurons collectively process input received from sensory organs, process the information, and decides what to do in reaction to the input. A typical neuron in the human nervous system has three main parts: dendrites, nucleus, and axons. The information passed to a neuron is received by dendrites. The nucleus is responsible for processing this information. The output of a neuron is passed to other neurons via the axon, which is connected to the dendrites of other neurons further down the network.
* ### Perceptron
Artificial neural networks are inspired by the human neural network architecture. The simplest neural network consists of only one neuron and is called a perceptron, as shown in the figure below:
![alt perceptron ](Images/perceptron.jpg)
A perceptron has one input layer and one neuron. Input layer acts as the dendrites and is responsible for receiving the inputs. The number of nodes in the input layer is equal to the number of features in the input dataset. Each input is multiplied with a weight (which is typically initialized with some random value) and the results are added together. The sum is then passed through an activation function. The activation function of a perceptron resembles the nucleus of human nervous system neuron. It processes the information and yields an output. In the case of a perceptron, this output is the final outcome. However, in the case of multilayer perceptrons, the output from the neurons in the previous layer serves as the input to the neurons of the proceeding layer.

* ### MultiLayer Perceptron
Now that we know what a single layer perceptron is, we can extend this discussion to multilayer perceptrons, or more commonly known as artificial neural networks. A single layer perceptron can solve simple problems where data is linearly separable in to 'n' dimensions, where 'n' is the number of features in the dataset. However, in case of non-linearly separable data, the accuracy of single layer perceptron decreases significantly. Multilayer perceptrons, on the other hand, can work efficiently with non-linearly separable data.
* ### In search of non linearity
* #### Feature crosses
![alt crosses ](https://)
However if we use a model that is too complicated, such as one with too many crosses, we give it the opportunity to fit to the noise in the training data, often at the cost of making the model perform badly on test data.
#### A neural network executes in two phases: Feed-Forward and Back Propagation.
* ## FeedForward
Following are the steps performed during the feed-forward phase:

 1. The values received in the input layer are multiplied with the weights. A bias is added to the summation of the inputs and weights in order to avoid null values.
 2. Each neuron in the first hidden layer receives different values from the input layer depending upon the weights and bias. Neurons have an activation function that operates upon the value received from the input layer. The activation function can be of many types, like a step function, sigmoid function, relu function, or tanh function. As a rule of thumb, relu function is used in the hidden layer neurons and sigmoid function is used for the output layer neuron.
  3. The outputs from the first hidden layer neurons are multiplied with the weights of the second hidden layer; the results are summed together and passed to the neurons of the proceeding layers. This process continues until the outer layer is reached. The values calculated at the outer layer are the actual outputs of the algorithm.

- The feed-forward phase consists of these three steps. However, the predicted output is not necessarily correct right away; it can be wrong, and we need to correct it. The purpose of a learning algorithm is to make predictions that are as accurate as possible. To improve these predicted results, a neural network will then go through a back propagation phase. During back propagation, the weights of different neurons are updated in a way that the difference between the desired and predicted output is as small as possible.

* ## BackPropagation
Back propagation phase consists of the following steps:

 1. The error is calculated by quantifying the difference between the predicted output and the desired output. This difference is called "loss" and the function used to calculate the difference is called the "loss function". Loss functions can be of different types e.g. mean squared error or cross entropy functions. Remember, neural networks are supervised learning algorithms that need the desired outputs for a given set of inputs, which is what allows it to learn from the data.
 2. Once the error is calculated, the next step is to minimize that error. To do so, partial derivative of the error function is calculated with respect to all the weights and biases. This is called gradient decent. The derivatives can be used to find the slope of the error function. If the slop is positive, the value of the weights can be reduced or if the slop is negative the value of weight can be increased. This reduces the overall error. The function that is used to reduce this error is called the optimization function.

- This one cycle of feed-forward and back propagation is called one "epoch". This process continues until a reasonable accuracy is achieved. There is no standard for reasonable accuracy, ideally you'd strive for 100% accuracy, but this is extremely difficult to achieve for any non-trivial dataset. In many cases 90%+ accuracy is considered acceptable, but it really depends on your use-case.

In [15]:
import numpy as np 
import pandas as pd

# Location of dataset
url = "Datasets/Iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Target']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=names) 
print(type(irisdata))
irisdata.head()

<class 'pandas.core.frame.DataFrame'>


sepal-length  sepal-width  petal-length  petal-width       Target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
print("Iris data set dimensions : {}".format(irisdata.shape))

Iris data set dimensions : (150, 5)


In [17]:
irisdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal-length    150 non-null float64
sepal-width     150 non-null float64
petal-length    150 non-null float64
petal-width     150 non-null float64
Target          150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [16]:
irisdata.isnull().sum()
irisdata.isna().sum()

sepal-length    0
sepal-width     0
petal-length    0
petal-width     0
Target          0
dtype: int64

In [5]:
# Assign data from first four columns to X variable
X = irisdata.iloc[:, 0:4]

# Assign data from first fifth columns to y variable
y = irisdata.select_dtypes(include=[object])  
y.head()

Target
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [6]:
a = y.Target.unique()  
print(a[0])

Iris-setosa


In [7]:
from sklearn import preprocessing  
le = preprocessing.LabelEncoder()

y = y.apply(le.fit_transform) 
y.Target.unique()
irisdata=irisdata.apply(le.fit_transform)

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns 
plt.figure(figsize=(10,10))
sns.heatmap(irisdata.astype(float).corr(),annot=True)
plt.show()

<Figure size 1000x1000 with 2 Axes>

In [9]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
print(y_train)

     Target
147       2
139       2
108       2
128       2
36        0
30        0
15        0
134       2
3         0
105       2
141       2
89        1
146       2
135       2
138       2
31        0
97        1
1         0
103       2
37        0
81        1
51        1
7         0
107       2
95        1
33        0
40        0
28        0
111       2
64        1
..      ...
96        1
113       2
123       2
43        0
70        1
94        1
38        0
115       2
2         0
42        0
48        0
77        1
137       2
143       2
22        0
20        0
26        0
54        1
19        0
122       2
56        1
47        0
45        0
74        1
27        0
114       2
10        0
102       2
53        1
14        0

[120 rows x 1 columns]


In [10]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test) 

In [11]:
from sklearn.neural_network import MLPClassifier  
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp.fit(X_train, y_train.values.ravel()) 

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [12]:
predictions = mlp.predict(X_test)  

In [13]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  

[[ 9  0  0]
 [ 0 11  0]
 [ 0  1  9]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       0.92      1.00      0.96        11
          2       1.00      0.90      0.95        10

avg / total       0.97      0.97      0.97        30



In [14]:
from sklearn.neural_network import MLPClassifier  
mlp = MLPClassifier(hidden_layer_sizes=(1), max_iter=1000)  
mlp.fit(X_train , y_train.values.ravel()) 
predictions = mlp.predict(X_test)  
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  

[[9 0 0]
 [1 4 6]
 [0 1 9]]
             precision    recall  f1-score   support

          0       0.90      1.00      0.95         9
          1       0.80      0.36      0.50        11
          2       0.60      0.90      0.72        10

avg / total       0.76      0.73      0.71        30



F:\Users\Redha\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
